// Per-request error logging with correlation IDs.
//
// Every API request gets an `x-request-id` (generated by middleware if the
// client didn't send one). When an API route catches an error, calling
// logError() prints a single greppable line AND forwards to Sentry tagged
// with the same id, so a customer report → server log → Sentry issue can
// all be linked via one string.
//
// Usage:
//   } catch (err) {
//     const reqId = logError('orders', err, { orderNumber, userId })
//     return NextResponse.json({ error: '...', reqId }, { status: 500 })
//   }
//
// Returning the id in the error response means support can ask the
// customer for the reqId and immediately find the matching Sentry trace.
import * as Sentry from '@sentry/nextjs'

export const REQUEST_ID_HEADER = 'x-request-id'

export function newRequestId(): string {
  // 12 hex chars — enough entropy for tracing, short enough for a
  // customer to read aloud. Avoid Node's crypto here because this
  // module is imported in the edge runtime (middleware).
  const bytes = new Uint8Array(6)
  crypto.getRandomValues(bytes)
  return Array.from(bytes, b => b.toString(16).padStart(2, '0')).join('')
}

export function getRequestId(request: Request | Headers): string {
  const headers = request instanceof Headers ? request : request.headers
  return headers.get(REQUEST_ID_HEADER) || newRequestId()
}

export interface LogContext {
  [key: string]: unknown
}

/**
 * Log a server error with a stable correlation id. Returns the reqId so
 * callers can include it in error responses for customer-facing tracing.
 */
export function logError(
  scope: string,
  error: unknown,
  context: LogContext & { reqId?: string; request?: Request | Headers } = {},
): string {
  const { reqId: explicitReqId, request, ...extras } = context
  const reqId = explicitReqId
    || (request ? getRequestId(request) : newRequestId())

  const message = error instanceof Error ? error.message : String(error)
  const tail = Object.keys(extras).length > 0 ? ` ${JSON.stringify(extras)}` : ''
  console.error(`[${scope}] [reqId=${reqId}] ${message}${tail}`,
    error instanceof Error ? error.stack : undefined)

  Sentry.withScope(scope_ => {
    scope_.setTag('request_id', reqId)
    scope_.setTag('scope', scope)
    for (const [k, v] of Object.entries(extras)) {
      scope_.setExtra(k, v)
    }
    if (error instanceof Error) {
      Sentry.captureException(error)
    } else {
      Sentry.captureMessage(`[${scope}] ${message}`, 'error')
    }
  })

  return reqId
}
