-- TMFoodStuff: Supabase schema for custom admin (Payload-free)
-- Safe to run in Supabase SQL Editor as a migration script.

begin;

create extension if not exists pgcrypto;

-- ============================================================
-- Enums
-- ============================================================
do $$ begin
  create type public.user_role as enum ('owner', 'manager', 'staff');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.product_unit as enum ('kg', 'g', 'piece', 'bunch', 'box', 'pack');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.order_status as enum (
    'pending',
    'confirmed',
    'processing',
    'out_for_delivery',
    'delivered',
    'cancelled'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.payment_method as enum ('cod', 'telr');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.payment_status as enum ('pending', 'paid', 'failed');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.delivery_slot as enum ('morning', 'afternoon', 'evening');
exception when duplicate_object then null; end $$;

-- ============================================================
-- Timestamps helper
-- ============================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

-- ============================================================
-- Admin identity/profile
-- auth.users is managed by Supabase Auth.
-- profiles links app roles to authenticated users.
-- ============================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role public.user_role not null default 'staff',
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

-- ============================================================
-- Media assets (replaces Payload media collection)
-- Store signed/public URL metadata for your admin UI.
-- ============================================================
create table if not exists public.media_assets (
  id bigint generated by default as identity primary key,
  bucket text not null default 'product-images',
  storage_path text not null unique,
  public_url text,
  alt_text text,
  width integer,
  height integer,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create trigger trg_media_assets_updated_at
before update on public.media_assets
for each row execute procedure public.set_updated_at();

-- ============================================================
-- Categories
-- ============================================================
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  name_ar text,
  slug text not null unique,
  description text,
  image_asset_id bigint references public.media_assets(id) on delete set null,
  emoji text,
  parent_id bigint references public.categories(id) on delete set null,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_by uuid references public.profiles(id),
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_categories_parent_id on public.categories(parent_id);
create index if not exists idx_categories_display_order on public.categories(display_order);
create index if not exists idx_categories_is_active on public.categories(is_active);

create trigger trg_categories_updated_at
before update on public.categories
for each row execute procedure public.set_updated_at();

-- ============================================================
-- Products
-- ============================================================
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  name_ar text,
  slug text not null unique,
  category_id bigint not null references public.categories(id) on delete restrict,
  description text,
  description_ar text,
  price_aed numeric(10,2) not null check (price_aed >= 0),
  compare_at_price_aed numeric(10,2) check (compare_at_price_aed is null or compare_at_price_aed >= 0),
  unit public.product_unit not null default 'kg',
  stock integer not null default 100 check (stock >= 0),
  is_active boolean not null default true,
  is_featured boolean not null default false,
  is_organic boolean not null default false,
  origin text,
  emoji text,
  image_url text,
  tags text[] not null default '{}',
  created_by uuid references public.profiles(id),
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_products_slug on public.products(slug);
create index if not exists idx_products_category_id on public.products(category_id);
create index if not exists idx_products_is_active on public.products(is_active);
create index if not exists idx_products_is_featured on public.products(is_featured);
create index if not exists idx_products_created_at on public.products(created_at desc);

create trigger trg_products_updated_at
before update on public.products
for each row execute procedure public.set_updated_at();

-- If you need multiple images per product, this replaces Payload "images" array.
create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  media_asset_id bigint references public.media_assets(id) on delete set null,
  image_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (media_asset_id is not null or image_url is not null)
);

create index if not exists idx_product_images_product_id on public.product_images(product_id);
create index if not exists idx_product_images_sort_order on public.product_images(sort_order);

create trigger trg_product_images_updated_at
before update on public.product_images
for each row execute procedure public.set_updated_at();

-- ============================================================
-- Customers + saved addresses
-- ============================================================
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  email text unique,
  full_name text,
  phone text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_customers_email on public.customers(email);
create index if not exists idx_customers_phone on public.customers(phone);

create trigger trg_customers_updated_at
before update on public.customers
for each row execute procedure public.set_updated_at();

create table if not exists public.customer_addresses (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  label text,
  building text,
  street text,
  area text,
  emirate text,
  makani text,
  is_default boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_customer_addresses_customer_id on public.customer_addresses(customer_id);
create index if not exists idx_customer_addresses_is_default on public.customer_addresses(customer_id, is_default);

create trigger trg_customer_addresses_updated_at
before update on public.customer_addresses
for each row execute procedure public.set_updated_at();

-- ============================================================
-- Orders + order items
-- ============================================================
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  customer_id bigint references public.customers(id) on delete set null,
  status public.order_status not null default 'pending',
  payment_method public.payment_method not null default 'cod',
  payment_status public.payment_status not null default 'pending',
  -- Customer snapshot (from Payload "customer" group)
  customer_full_name text,
  customer_phone text,
  customer_email text,
  -- Delivery snapshot (from Payload "delivery" group)
  delivery_emirate text,
  delivery_area text,
  delivery_building text,
  delivery_makani text,
  delivery_slot public.delivery_slot,
  delivery_notes text,
  -- Pricing (from Payload "pricing" group)
  subtotal_aed numeric(10,2) not null default 0 check (subtotal_aed >= 0),
  vat_aed numeric(10,2) not null default 0 check (vat_aed >= 0),
  delivery_fee_aed numeric(10,2) not null default 0 check (delivery_fee_aed >= 0),
  promo_code text,
  promo_discount_aed numeric(10,2) not null default 0 check (promo_discount_aed >= 0),
  total_aed numeric(10,2) not null check (total_aed >= 0),
  placed_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_orders_order_number on public.orders(order_number);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_payment_status on public.orders(payment_status);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_orders_customer_id on public.orders(customer_id);

create trigger trg_orders_updated_at
before update on public.orders
for each row execute procedure public.set_updated_at();

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit public.product_unit,
  unit_price_aed numeric(10,2) not null check (unit_price_aed >= 0),
  subtotal_aed numeric(10,2) not null check (subtotal_aed >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_order_items_product_id on public.order_items(product_id);

create trigger trg_order_items_updated_at
before update on public.order_items
for each row execute procedure public.set_updated_at();

-- ============================================================
-- Optional: order event audit log
-- ============================================================
create table if not exists public.order_events (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  event_type text not null,
  event_payload jsonb not null default '{}'::jsonb,
  performed_by uuid references public.profiles(id),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_order_events_order_id on public.order_events(order_id);
create index if not exists idx_order_events_created_at on public.order_events(created_at desc);

-- ============================================================
-- RLS helper functions
-- ============================================================
create or replace function public.current_user_role()
returns public.user_role
language sql
stable
as $$
  select role
  from public.profiles
  where id = auth.uid()
  limit 1
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select coalesce(public.current_user_role() in ('owner', 'manager'), false)
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
as $$
  select coalesce(public.current_user_role() in ('owner', 'manager', 'staff'), false)
$$;

-- ============================================================
-- Enable RLS everywhere
-- ============================================================
alter table public.profiles enable row level security;
alter table public.media_assets enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.customers enable row level security;
alter table public.customer_addresses enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_events enable row level security;

-- ============================================================
-- Profiles policies
-- ============================================================
drop policy if exists "profiles self read" on public.profiles;
create policy "profiles self read"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists "profiles self update" on public.profiles;
create policy "profiles self update"
on public.profiles for update
to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

drop policy if exists "profiles admin insert" on public.profiles;
create policy "profiles admin insert"
on public.profiles for insert
to authenticated
with check (public.is_admin() or id = auth.uid());

-- ============================================================
-- Catalog policies (storefront read for anon/auth, write for staff+)
-- ============================================================
drop policy if exists "categories public read active" on public.categories;
create policy "categories public read active"
on public.categories for select
to anon, authenticated
using (is_active = true or public.is_staff());

drop policy if exists "categories staff write" on public.categories;
create policy "categories staff write"
on public.categories for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

drop policy if exists "products public read active" on public.products;
create policy "products public read active"
on public.products for select
to anon, authenticated
using (is_active = true or public.is_staff());

drop policy if exists "products staff write" on public.products;
create policy "products staff write"
on public.products for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

drop policy if exists "product_images public read" on public.product_images;
create policy "product_images public read"
on public.product_images for select
to anon, authenticated
using (true);

drop policy if exists "product_images staff write" on public.product_images;
create policy "product_images staff write"
on public.product_images for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

drop policy if exists "media_assets public read" on public.media_assets;
create policy "media_assets public read"
on public.media_assets for select
to anon, authenticated
using (true);

drop policy if exists "media_assets staff write" on public.media_assets;
create policy "media_assets staff write"
on public.media_assets for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

-- ============================================================
-- Customer policies
-- ============================================================
drop policy if exists "customers admin read all" on public.customers;
create policy "customers admin read all"
on public.customers for select
to authenticated
using (public.is_staff() or auth_user_id = auth.uid());

drop policy if exists "customers self insert_or_update" on public.customers;
create policy "customers self insert_or_update"
on public.customers for all
to authenticated
using (public.is_staff() or auth_user_id = auth.uid())
with check (public.is_staff() or auth_user_id = auth.uid());

drop policy if exists "customer_addresses owner or admin" on public.customer_addresses;
create policy "customer_addresses owner or admin"
on public.customer_addresses for all
to authenticated
using (
  public.is_staff()
  or exists (
    select 1 from public.customers c
    where c.id = customer_addresses.customer_id
      and c.auth_user_id = auth.uid()
  )
)
with check (
  public.is_staff()
  or exists (
    select 1 from public.customers c
    where c.id = customer_addresses.customer_id
      and c.auth_user_id = auth.uid()
  )
);

-- ============================================================
-- Order policies
-- ============================================================
drop policy if exists "orders staff full access" on public.orders;
create policy "orders staff full access"
on public.orders for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

drop policy if exists "orders customer read own" on public.orders;
create policy "orders customer read own"
on public.orders for select
to authenticated
using (
  exists (
    select 1
    from public.customers c
    where c.id = orders.customer_id
      and c.auth_user_id = auth.uid()
  )
);

drop policy if exists "orders customer create own" on public.orders;
create policy "orders customer create own"
on public.orders for insert
to authenticated
with check (
  exists (
    select 1
    from public.customers c
    where c.id = orders.customer_id
      and c.auth_user_id = auth.uid()
  )
);

drop policy if exists "order_items staff full access" on public.order_items;
create policy "order_items staff full access"
on public.order_items for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

drop policy if exists "order_items customer read own" on public.order_items;
create policy "order_items customer read own"
on public.order_items for select
to authenticated
using (
  exists (
    select 1
    from public.orders o
    join public.customers c on c.id = o.customer_id
    where o.id = order_items.order_id
      and c.auth_user_id = auth.uid()
  )
);

drop policy if exists "order_events staff only" on public.order_events;
create policy "order_events staff only"
on public.order_events for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

-- ============================================================
-- Grants
-- ============================================================
grant usage on schema public to anon, authenticated;
grant select on public.categories, public.products, public.product_images, public.media_assets to anon;
grant select on all tables in schema public to authenticated;
grant insert, update, delete on all tables in schema public to authenticated;

-- Existing sequence grants for identity columns
grant usage, select on all sequences in schema public to authenticated;

commit;

-- NOTE:
-- Your server-side admin routes can continue to use service role key.
-- RLS still protects all client-side calls from the browser.
